# Generated by Django 2.2.7 on 2021-08-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArgUsers', '0004_auto_20210804_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='argprofile',
            old_name='image',
            new_name='test',
        ),
    ]
