# Generated by Django 2.2.7 on 2021-08-04 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArgUsers', '0005_auto_20210804_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='argprofile',
            old_name='test',
            new_name='pict',
        ),
    ]
