# Generated by Django 3.2.5 on 2021-08-28 16:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Argupedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arg_Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arg_date', models.DateTimeField(default=datetime.datetime.now)),
                ('information', models.TextField()),
                ('argupedia_topic', models.TextField(blank=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArgFuture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arg_future_plans_title', models.TextField()),
                ('arg_future_plans_detail', models.TextField()),
                ('arg_future_date', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArgPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.TextField()),
                ('arg_content', models.TextField()),
                ('arg_date_posted', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArgProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specalist', models.CharField(max_length=50)),
                ('pict', models.ImageField(default='default.jpg', upload_to='arguserpic')),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Argument_Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Argument_field_name', models.TextField(blank=True)),
                ('Argument_field', models.TextField(blank=True)),
                ('Argument_source', models.TextField(blank=True)),
                ('Argument_additional_info', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Argument_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Argument_Name', models.TextField()),
                ('Argument_information', models.TextField(blank=True)),
                ('Argument_source', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contactinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CQ', models.TextField()),
                ('Argument_source', models.TextField(blank=True)),
                ('Argument_additional_info', models.TextField(blank=True)),
                ('choice', models.BooleanField()),
                ('Argument_crit_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Argupedia.argument_name')),
            ],
        ),
        migrations.CreateModel(
            name='reportPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_reporting', models.TextField(blank=True)),
                ('user_reported', models.EmailField(max_length=254)),
                ('reason', models.TextField()),
                ('urllink', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='video/%y')),
            ],
        ),

        migrations.AddField(
            model_name='argument_fields',
            name='Argument_name_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Argupedia.argument_name'),
        ),
        migrations.AddField(
            model_name='arg_posts',
            name='Argument_name_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Argupedia.argument_name'),
        ),
        migrations.AddField(
            model_name='arg_posts',
            name='Categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Argupedia.categories'),
        ),
        migrations.AddField(
            model_name='arg_posts',
            name='argupedia_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arg_posts',
            name='cqs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cqs', to='Argupedia.cq'),
        ),
        migrations.AddField(
            model_name='arg_posts',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Argupedia.arg_posts'),
        ),
        migrations.AddField(
            model_name='arg_posts',
            name='votedown',
            field=models.ManyToManyField(blank=True, related_name='votedown', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arg_posts',
            name='voteup',
            field=models.ManyToManyField(blank=True, related_name='voteup', to=settings.AUTH_USER_MODEL),
        ),
    ]
