# Generated by Django 3.2.5 on 2021-08-29 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Argupedia', '0003_auto_20210829_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='argprofile',
            old_name='profile_picture',
            new_name='pict',
        ),
    ]
