# Generated by Django 3.2.5 on 2021-08-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Argupedia', '0006_alter_argprofile_specalist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argprofile',
            name='specalist',
            field=models.CharField(max_length=40),
        ),
    ]
