# Generated by Django 3.2.5 on 2021-09-01 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Argupedia', '0007_alter_argprofile_specalist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='argpost',
            options={'verbose_name_plural': 'Announcements'},
        ),
    ]
