# Generated by Django 3.2.5 on 2021-09-02 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Argupedia', '0008_alter_argpost_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arg_posts',
            old_name='Argument_name_post',
            new_name='Argument_scheme',
        ),
    ]
