# Generated by Django 3.2.5 on 2021-09-02 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Argupedia', '0009_rename_argument_name_post_arg_posts_argument_scheme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arg_posts',
            old_name='Argument_scheme',
            new_name='Argument_name_post',
        ),
    ]
